### PR TITLE
Set up CORS (Cross Origin Resource Sharing) which lets the extension …

### PR DESCRIPTION
**Pull request by Steven-Eardley**
…send stuff to it (browsers are fussy about CORS)

* new requirement: flask-cors.
* changed deprecated call in core.py
* additions to .gitignore

### CODE REVIEW

**Comment by Steven-Eardley** [comment]
@markmacgillivray @anusharanganathan [CORS](https://pypi.python.org/pypi/Flask-Cors/) support is needed for the extension to talk to the API. This PR takes care of that, and should be deployed ASAP for any demos!

**Comment by anusharanganathan** [comment]
Ah, didn't know flask had a CORS extension. Thanks Steve. I don't have access to the test server, so I guess I'll leave it to Mark to merge this PR and deploy the changes.

**Comment by markmacgillivray** [comment]
Hi Steve, Anusha - do not merge this change. It is unlikely to be
necessary. Yes, CORS is required for the apps to function cross-domain, but
it is not necessary to code it into the app itself - it can and should be
handled at the nginx layer. Only if we have issues there, for some reason,
should we augment the app for that particular issue. I will check the nginx
configs then we can test the code as is first before taking this step.

Mark

**Comment by Steven-Eardley** [comment]
Okay, I also found it's required when talking to the extension in dev, via localhost:5004

**Comment by markmacgillivray** [comment]
Yes, to localhost it may fail because you do not configure your local
server to allow it. However, if you serve locally via nginx with the
necessary config, or just do your tests against the deployed app, you
should find it works ok. I just checked and the nginx config already allows
* for https://webber.cottagelabs.com so try against that and see if it
allows or not.

**Comment by Steven-Eardley** [comment]
I'm definitely getting an error related to CORS:
```
XMLHttpRequest cannot load https://webber.cottagelabs.com/am_i_in. Request header field X-apikey is not allowed by Access-Control-Allow-Headers in preflight response.
```

**Comment by markmacgillivray** [comment]
Well that's not a CORS error, it's an allow-headers error. Because I didn't
know the name of the header anusha would use, it's not in the list of
allowed headers. That should still be fixable at the web server layer
though. I'll check those settings in the morning. I prefer to keep software
as minimal as possible, and leave problems and their solutions to the
layers where they are unavoidable anyway. So unless we must handle it in
the software using flask-cors (or another method) then we shouldn't. That
way our creations stay simple and less brittle and easier to maintain (and
easier to make).

**Comment by markmacgillivray** [comment]
Sorry I mean it is not an origin problem, but yes a header problem. Should
still be solvable by nginx config.

Mark

**Comment by markmacgillivray** [comment]
I've tried changing the nginx settings now, although it may take more
fiddling. Have a go and see.

**Comment by Steven-Eardley** [comment]
Auth worked fine! Now /visit, please :)

```
XMLHttpRequest cannot load https://webber.cottagelabs.com/visit. Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.
```

**Comment by markmacgillivray** [comment]
Ah of course you need PUT too. OK I have added that and DELETE just in case.

**Comment by Steven-Eardley** [comment]
Still getting same error as above

**Comment by markmacgillivray** [comment]
OK sorry I did not add to the preflight. Should be ok now.

Mark

**Comment by Steven-Eardley** [comment]
Sorted.

**Pull request closed without merging**
